#!/usr/bin/env python3

import random
import math
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl


def read_data(path):
    """
    Read the input file and store it in data_set.

    DO NOT CHANGE SIGNATURE OF THIS FUNCTION

    Args:
    path: path to the dataset

    Returns:
    data_set: a list of data points, each data point is itself a list of features:
    [
    [x_1, ..., x_n],
    ...
    [x_1, ..., x_n]
    ]
    """
    data_set = []
    y = -1
    with open(path, "r") as file:
        for line in file:
            y = y+1
            data_set.append([])
            currentline = line.split(",")
            for x in currentline:
                data_set[y].append(float(x.rstrip()))
    return data_set



def init_centers_random(data_set, k):
    """
    Initialize centers by selecting k random data points in the data_set.

    DO NOT CHANGE SIGNATURE OF THIS FUNCTION

    Args:
        data_set: a list of data points, where each data point is a list of features.
        k: the number of mean/clusters.

    Returns:
        centers: a list of k elements: centers initialized using random k data points in your data_set.
                 Each center is a list of numerical values. i.e., 'vals' of a data point.
    """
    data = []
    for x in data_set:
        data.append(x)

    centers = []
    for x in range(0,k):
        t = random.choice(data)
        centers.append(t)
        data.remove(t)
    return centers



def dist(vals, center):
    """
    Helper function: compute the euclidean distance from a data point to the center of a cluster

    Args:
        vals: a list of numbers (i.e. 'vals' of a data_point)
        center: a list of numbers, the center of a cluster.

    Returns:
         d: the euclidean distance from a data point to the center of a cluster
    """
    neg = []
    for x in center:
        neg.append(-1*x)
    sub = vect_add(vals, neg)
    total = 0
    for y in sub:
        total = total + (y*y)
    d = math.sqrt(total)
    return d





def get_nearest_center(vals, centers):
    """
    Assign a data point to the cluster associated with the nearest of the k center points.
    Return the index of the assigned cluster.

    Args:
        vals: a list of numbers (i.e. 'vals' of a data point)
        centers: a list of center points.

    Returns:
        c_idx: a number, the index of the center of the nearest cluster, to which the given data point is assigned to.
    """
    index = -1
    best = dist(vals, centers[0])
    best_index = 0
    for x in centers:
        index = index + 1
        temp_value = dist(vals, x)
        if (best > temp_value):
            best = temp_value
            best_index = index
    return best_index



def vect_add(x, y):
    """
    Helper function for recalculate_centers: compute the element-wise addition of two lists.
    Args:
        x: a list of numerical values
        y: a list of numerical values

    Returns:
        s: a list: result of element-wise addition of x and y.
    """
    s=[]
    for i in range(0,len(x)):
        s.append(x[i]+y[i])

    return s


def vect_avg(s, n):
    """
    Helper function for recalculate_centers: Averaging n lists.
    Args:
        s: a list of numerical values: the element-wise addition over n lists.
        n: a number, number of lists

    Returns:
        s: a list of numerical values: the averaging result of n lists.
    """

    new_one =  []
    for y in s[0]:
        new_one.append(0)
    for x in range(0,len(s)):
        m = []
        for i in range(0,len(new_one)):
            m.append(new_one[i]+s[x][i])
        new_one = m

    answer = []
    for y in new_one:
        answer.append(y/len(s))

    return answer



def recalculate_centers(clusters):
    """
    Re-calculate the centers as the mean vector of each cluster.
    Args:
         clusters: a list of clusters. Each cluster is a list of data_points assigned to that cluster.

    Returns:
        centers: a list of new centers as the mean vector of each cluster.
    """
    centers = []

    for x in clusters:
        new_center = vect_avg(x, len(x))
        if(new_center == None or new_center == []):
            return None
        centers.append(new_center)
    return centers



def train_kmean(data_set, centers, iter_limit):
    """
    DO NOT CHANGE SIGNATURE OF THIS FUNCTION

    Args:
        data_set: a list of data points, where each data point is a list of features.
        centers: a list of initial centers.
        iter_limit: a number, iteration limit

    Returns:
        centers: a list of updates centers/mean vectors.
        clusters: a list of clusters. Each cluster is a list of data points.
        num_iterations: a number, num of iteration when converged.
    """

    iterations = 0

    while(iterations < iter_limit):
        iterations = iterations + 1
        clusters = []
        for i in centers:
            clusters.append([])
        for x in data_set:
            clusters[get_nearest_center(x, centers)].append(x)

        new_centers = recalculate_centers(clusters)
        if(new_centers == None):
            centers = init_centers_random(data_set, len(centers))
        elif(new_centers == centers):
            return centers, clusters, iterations
        else:
            centers = []
            for k in new_centers:
                centers.append(k)

    return centers, clusters, iterations


def within_cluster_ss(cluster, center):
    """
    For each cluster, compute the sum of squares of euclidean distance
    from each data point in the cluster to the empirical mean of this cluster.
    Please note that the euclidean distance is squared in this function.

    Args:
        cluster: a list of data points.
        center: the center for the given cluster.

    Returns:
        ss: a number, the within cluster sum of squares.
    """
    ss = 0
    for x in cluster:
        distance = dist(x, center)
        ss = ss + (distance*distance)
    return ss


def sum_of_within_cluster_ss(clusters, centers):
    """
    For total of k clusters, compute the sum of all k within_group_ss(cluster).

    DO NOT CHANGE SIGNATURE OF THIS FUNCTION

    Args:
        clusters: a list of clusters.
        centers: a list of centers of the given clusters.

    Returns:
        sss: a number, the sum of within cluster sum of squares for all clusters.
    """
    sss=0
    for x in range(0, len(clusters)):
        sss = sss + within_cluster_ss(clusters[x], centers[x])
    return sss

